### ISSUE TITLE
Issues with frames in userSequenceDiagram

### ISSUE THREAD

**Issue by wenxin-c** [AY2425S1-CS2113-W12-1/tp#115]
If ```opt``` or ```alt``` frames conditions are fullfilled and ```userDataFile``` object is activated, it should be included in the frames as well rather than only include ```historyTracker``` object in the frame. 
![image](https://github.com/user-attachments/assets/1a8058ea-e1e6-420a-a003-8f80d0232fd2)
The following is a screenshot from course website for your reference:
![image](https://github.com/user-attachments/assets/c6e371ca-1ca4-4f52-a50e-bddd29951a55)

**Comment by kennethSty** [comment]
Done
