### ISSUE TITLE
Issue with Obejct Deletion in userSequenceDiagram

### ISSUE THREAD

**Issue by wenxin-c** [AY2425S1-CS2113-W12-1/tp#116]
Should ```user``` object be deleted after the condition frames since they are only created in the frame (i.e. indicate a cross at the end of lifeline)?
![image](https://github.com/user-attachments/assets/5362056c-04aa-4ea9-ae48-394da914178a)

**Comment by kennethSty** [comment]
Thanks for this comment.
The user instance is created and will continue to exist after creation. 
The diagram shows two different paths of the program which each lead to one new user instance. In the one path, the user data is loaded and a new user instance is created from the loaded information. 
In the other case, the user data is retrieved by asking the user. 

So at the end of the full sequence, we have one user instance that continues to exist (not two :)). By stopping the lifelines without a cross I tried to visualize this. 

What would be the correct visualization?

**Comment by kennethSty** [comment]
@wenxin-c could you pls help me here find the correct way of drawing it? :)

**Comment by wenxin-c** [comment]
Hi, your explanation makes sense and you could use your existing drawing given the context.

**Comment by kennethSty** [comment]
thanks!
