### ISSUE TITLE
Implement user initialisation workflow

### ISSUE THREAD

**Issue by kennethSty** [AY2425S1-CS2113-W12-1/tp#13]
If a user file storing user specifics does not exist or is empty, ask the user to enter a HEALTH_GOAL, weight and height. Afterwards, start with the general usage flow (adding mealEntries, saving meals etc.)

**Comment by ryryry-3302** [comment]
I think naming this issue as user initialisation would be more apt as user registration sounds like creating login processes to me

**Comment by kennethSty** [comment]
Done as part of #69
