### ISSUE TITLE
[PE-D][Tester C] Case Sensitivity for Health Goal Input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W12-1/tp#155]
![image.png](https://raw.githubusercontent.com/YukeeHong/ped/main/files/3904a872-91cf-4919-b1f0-43b17763ec55.png)
Making the input case-insensitive or automatically converting it to uppercase may improve usability and reduce errors.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: YukeeHong/ped#1

**Comment by kennethSty** [comment]
Done.
