### ISSUE TITLE
[PE-D][Tester E] CSV handling for meal_entries

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W12-1/tp#198]
![csv_manual_alterations.png](https://raw.githubusercontent.com/tayjerom/ped/main/files/94f4da58-8aa8-4143-afba-a4e9e7e26018.png)

Application shows no meal entries after intentionally deleting a column off the CSV file - does not display meal entries.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tayjerom/ped#8

**Comment by kennethSty** [comment]
Fixed here: #210

**Comment by kennethSty** [comment]
Fix includes:
1. Inform the user about corrupted data
2. give the user the choice to:
a) Close the application and redo the changes to not lose the data
b) Proceed using the app and accept that old data will be overwritten with new data.
