### ISSUE TITLE
[PE-D][Tester A] Incorrect naming convention of the user entity in sequence diagram

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-1/tp#202]
![image.png](https://raw.githubusercontent.com/Chiang-HuiXin/ped/main/files/1c73ba5b-ddf5-4b8a-81cf-3807f95667da.png)

I think that the /<<class>>/ should not be there and it should be :User

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Chiang-HuiXin/ped#11

**Comment by kennethSty** [comment]
Wrong report. It is a call to a static method of the User class. 

code:  `public static User  askForUserData() `
<img width="703" alt="image" src="https://github.com/user-attachments/assets/2802981a-d91b-423b-874d-ae995e9b90db">
