### ISSUE TITLE
How do we identify meals? 

### ISSUE THREAD

**Issue by kennethSty** [AY2425S1-CS2113-W12-1/tp#23]
How do we identify meals? 

**Suggestion: By name.** 
Reason: allows the user to track a meal via easy commands. 

Assume he already added "burger" to the list of meal options. 

Then `add mealEntry burger` would be enough to track the meal for today. 

Potential consequence: make `MealList mealOptions` not a list but a set for quicker retrieval.

**Comment by ryryry-3302** [comment]
Sounds like a good idea to me.
