### ISSUE TITLE
new Command: Show progress bar for each day in a timeframe

### ISSUE THREAD

**Issue by kennethSty** [AY2425S1-CS2113-W12-1/tp#70]
As a user I want to see a timeline overview for a certain timerange to check how often I reached my desired calorie intake goal

**Comment by DarkDragoon2002** [comment]
I've created Commands to see historicCalories and todayCalories. 
You can specify the number of days back you would like to see in historicCalories. It will print out the progress Bars for each day with the date beside them. 

I also edited the Bar printing function to ensure the bars stay the same length when there are different percentages inside the square brackets. eg. (1% vs 25% vs 180%)
