### ISSUE TITLE
Implement User Log File

### ISSUE THREAD

**Issue by ryan-txn** [AY2425S1-CS2113-W12-1/tp#85]
- [x] Convert current text file to use csv file
- [x] Change current User class to UserEntry for clarity
- [x] Create new UserEntryList class for easier deleting / finding of UserEntry from saved data
- [x] Create new UserHistoryTracker to maintain SRP
- [x] Update logic to ask for new userdata when first starting app and creating new file
- [x] Csv File saves multiple UserEntry instances
- [x] Csv file can load multiple UserEntry instances
- [x] Print user data entries command
- [x] Clear user data entries command

**Comment by kennethSty** [comment]
@ryan-txn I would deprioritize task 2 and three. Having multiple users is not as essential as other features (especially regarding v2.1)

**Comment by kennethSty** [comment]
Please also consider writing test code to ensure everything is stable :)
